### Forms Index
GET http://localhost:3000/forms.json

### Forms Create
POST http://localhost:3000/forms.json
Content-Type: application/json

{
"name": "Appointments"
}

### Forms Show
GET http://localhost:3000/forms/1.json

### Forms Update
PATCH http://localhost:3000/forms/1.json
Content-Type: application/json

{
"name":"test"
}

### Forms Destroy
DELETE http://localhost:3000/forms/44

### Products Index
GET http://localhost:3000/products.json

### Products Create
POST http://localhost:3000/products.json
Content-Type: application/json

{
"name": "Pastle Denona Eyeshadow Palette",
"brand": "Natasha Denona",
"image_url": "https://www.sephora.com/productimages/sku/s2512556-av-01-zoom.jpg?imwidth=612",
"department": "Face",
"description": "A palette bursting with lush, inspiring colors from playful pinks and yellows to delicate purples and blues.",
"available_at":"Sephora",
"catagory":"Makeup", 
"sub_catagory":"Face",
"form_id": 1,
"media":""
}

### Products Show
GET http://localhost:3000/products/3.json

### Products Update
PATCH http://localhost:3000/products/5.json


{
"name": "Test update",
"brand": "test update",
"image_url": "test",
"department": "test dept update",
"description": "test update",
"available_at":"test update",
"catagory":"test update", 
"sub_catagory":"test update",
"key_word":"test update",
"tutorial_id": 12345, 
"product_id": 1234,
}

### Products Destroy
DELETE http://localhost:3000/products/4.json

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Harry",
  "email": "styles@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Key_words Index
GET http://localhost:3000/key_words.json

### Key_Words Create
POST http://localhost:3000/key_words.json
Content-Type: application/json

{
"key_word": "Bored",
"product_id": 25,
"answer_id": 10
}

### Key_words Show
GET http://localhost:3000/key_words/16.json

### Key_words Update
PATCH http://localhost:3000/key_words/1.json
Content-Type: application/json

{
"key_word": "Round",
"product_id": "8"
}

### Key_words Destroy
DELETE http://localhost:3000/key_words/

###Answers Create
POST http://localhost:3000/answers.json
Content-Type: application/json

{
"answer":"I want to learn how to contour my face",
"question_id":10
}

### Answers Index
GET http://localhost:3000/answers

### Answers Show
GET http://localhost:3000/answers/14.json


###Users_Answers
POST http://localhost:3000/users_answers.json
Content-Type: application/json

{
"answer_id":3,
"question_id":1,
"user_id": 1
}

### Users_Answers Index
GET http://localhost:3000/users_answers