### Forms Index
GET http://localhost:3000/forms.json

### Forms Create
POST http://localhost:3000/forms.json
Content-Type: application/json

{
"name": "Appointments"
}

### Forms Show
GET http://localhost:3000/forms/1.json

### Forms Update
PATCH http://localhost:3000/forms/1.json
Content-Type: application/json

{
"name":"test"
}

### Forms Destroy
DELETE http://localhost:3000/forms/44

### Products Index
GET http://localhost:3000/products.json

### Products Create
POST http://localhost:3000/products.json
Content-Type: application/json

{
"name": "Major Sculpt - Creme Contour & Powder Bronzer Duo",
"brand": "Patrick Ta",
"image_url": "https://cdn.shopify.com/s/files/1/0099/0602/8608/products/Medium-She_sSculpted-Allure_86d358a3-6ee4-49d3-9dde-90d31e805a8d_large.png?v=1633496390",
"department": "Bronzer",
"description": "bronzer for bronzing",
"available_at":"Sephora, Patrick Ta, Amazon",
"catagory":"Makeup", 
"sub_catagory":"Face",
"tutorial_id":2,
"form_id": 1,
"media":""
}

### Products Show
GET http://localhost:3000/products/3.json

### Products Update
PATCH http://localhost:3000/products/5.json


{
"name": "Test update",
"brand": "test update",
"image_url": "test",
"department": "test dept update",
"description": "test update",
"available_at":"test update",
"catagory":"test update", 
"sub_catagory":"test update",
"key_word":"test update",
"tutorial_id": 12345, 
"product_id": 1234,
}

### Products Destroy
DELETE http://localhost:3000/products/4.json

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Harry",
  "email": "styles@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Key_words Index
GET http://localhost:3000/key_words.json

### Key_words Create
POST http://localhost:3000/key_words.json
Content-Type: application/json

{
"key_word": "eyeshadow",
"product_id": "2"
}

### Key_words Show
GET http://localhost:3000/key_words/1.json

### Key_words Update
PATCH http://localhost:3000/key_words/1.json
Content-Type: application/json

{
"key_word": "test update",
"key_word_id": "123",
"product_id": "2"
}

### Key_words Destroy
DELETE http://localhost:3000/key_words/2