Form.create(question:"What is your face shape? Circle, square, heart, diamond, rectangle or oval",)
Form.create(question:"Which celebrity does your skin tone most closely match? Elle Fanning, Jessica Biel, Lucy Liu, Mila Kunis,Jessica Alba, Beyonce, Mindy Kahling, or Jennifer Hudson.",)
Form.create(question:"What skin issue do you struggle with most?",)
Form.create(question:"Do you prefer a more natural or glam look?",)
Form.create(question:"What colors do you reach for when pick out blushes and lipsticks?",)
Form.create(question:"Do you prefer products with shine-finish or matte?",)
Form.create(question:"How much time do you have for a beauty routine in the beginning of your day?",)
Form.create(question:"Do you prefer best within a budget products or high end?",)
Form.create(question:"What is an eye makeup technique you would like to perfect?",)
Form.create(question:"What is an issue with makeup you would like to resolve?",)

Product.create(name:"Luxury Eyeshadow Palette", brand:"Charlotte Tilbury", description:"Each palette contains four harmonious eye colors: Prime, Enhance, Smoke, and Pop. Create a smooth base for your eye look using the Prime shade; build up definition with Enhance; add drama with the Smoke shade; and finish your dazzling look with the shimmer Pop shade. The collection can be built for a day, desk, dusk, or disco look. The step by step application is artistry made easy.", available_at:"Sephora, Nordstrom, Company Website", department: "Eyeshadow", catagory:"Makeup",sub_catagory:"Eyes", key_word:"luxury, glam, eyeshadow palettes", tutorial_id:1, product_id:111,)