Form.create(question:"What is your face shape? Circle, square, heart, diamond, rectangle or oval",)
Form.create(question:"Which celebrity does your skin tone most closely match? Elle Fanning, Jessica Biel, Lucy Liu, Mila Kunis,Jessica Alba, Beyonce, Mindy Kahling, or Jennifer Hudson.",)
Form.create(question:"What skin issue do you struggle with most?",)
Form.create(question:"Do you prefer a more natural or glam look?",)
Form.create(question:"What colors do you reach for when pick out blushes and lipsticks?",)
Form.create(question:"Do you prefer products with shine-finish or matte?",)
Form.create(question:"How much time do you have for a beauty routine in the beginning of your day?",)
Form.create(question:"Do you prefer best within a budget products or high end?",)
Form.create(question:"What is an eye makeup technique you would like to perfect?",)
Form.create(question:"What is an issue with makeup you would like to resolve?")
